# Generated by Django 3.2.9 on 2022-11-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bill_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(max_length=30)),
                ('bill_id', models.CharField(max_length=200)),
                ('price', models.IntegerField(null=True)),
                ('bill_period', models.CharField(max_length=100)),
                ('entity', models.CharField(max_length=30)),
                ('reference', models.CharField(max_length=30)),
                ('limit_date', models.DateTimeField(verbose_name='limit date')),
            ],
        ),
    ]
